# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlEC_OI6eyVWJbmDdEJN2XK7aZD_jFrQ
"""

import pandas
import pandas as pd

#Dados Relativos à pandemia COVID-19 em Portugal
#Página do dado: https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv
dados_capes_cc = pd.read_csv("https://raw.githubusercontent.com/dssg-pt/covid19pt-data/refs/heads/master/data.csv")
dados_capes_cc.head(15)

dados_capes_cc.tail(15)

dados_capes_cc.info()

dados_capes_cc.describe()

dados_capes_cc['internados'].plot(kind="hist")

#Dados Relativos à pandemia COVID-19 no Brasil
#Página do dado: https://raw.githubusercontent.com/henriquemor/covid19-Brazil-timeseries/refs/heads/master/confirmed-cases.csv
dados_capes_cc = pd.read_csv("https://raw.githubusercontent.com/henriquemor/covid19-Brazil-timeseries/refs/heads/master/confirmed-cases.csv")
dados_capes_cc.head(15)