# -*- coding: utf-8 -*-
"""ProcessamentoDeDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlEC_OI6eyVWJbmDdEJN2XK7aZD_jFrQ
"""

import pandas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Dados Relativos à pandemia COVID-19 no mundo
#Página do dado: https://github.com/owid/covid-19-data
dados_capes_cc = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/refs/heads/master/public/data/owid-covid-data.csv")


#Filtrar dados apenas dos países desejados
paises_desejados = ['Portugal', 'Chile', 'Brazil', 'Russia']
dados_capes_cc = dados_capes_cc[dados_capes_cc['location'].isin(paises_desejados)]
dados_capes_cc.head(15)

dados_capes_cc.tail(15)

dados_capes_cc.info()

dados_capes_cc.describe()

#Estilo
sns.set(style='whitegrid')
plt.rcParams["figure.figsize"] = (14,6)

#Filtrando Colunas
dados = dados[['location', 'date', 'new_deaths_smoothed', 'people_vaccinated']]

#Selecionar Países de Interesse
paises = ['Portugal', 'Chile', 'Brazil', 'Russia']
dados = dados_capes_cc[dados_capes_cc['location'].isin(paises)]

#Converter data para datetime
dados_capes_cc['date'] = pd.to_datetime(dados_capes_cc['date'])


#Criar gráficos individuais por país
for pais in paises:
    pais_dados = dados[dados['location'] == pais]

    # Encontrar o primeiro dia em que começou a vacinação
    inicio_vacinacao = pais_dados[pais_dados['people_vaccinated'].notna()].date.min()

    # Plotando
    plt.figure(figsize=(14,6))
    plt.plot(pais_dados['date'], pais_dados['new_deaths_smoothed'], label='Mortes diárias (suavizadas)', color='red')
    plt.axvline(inicio_vacinacao, color='green', linestyle='--', label=f'Início da vacinação: {inicio_vacinacao.date()}')
    plt.title(f'{pais}: Mortes x Início da Vacinação')
    plt.xlabel('Data')
    plt.ylabel('Mortes por dia (média móvel)')
    plt.legend()
    plt.tight_layout()
    plt.show()